services:
  crypto-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: crypto-bot:latest
    container_name: crypto-bot
    volumes:
      # Configuration directory
      - ./user-config:/usr/src/app/user-config
      # Asset positions data directory
      - ./asset-positions:/usr/src/app/asset-positions
      # Logs directory (if created)
      - ./logs:/usr/src/app/logs
      # Sync timezone with host
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      